### ISSUE TITLE
Add get started section

### ISSUE THREAD

**Issue by etroynov** [etroynov/zig-school#5]
It should like this:
<img width="296" alt="Screenshot 2023-10-08 at 18 32 22" src="https://github.com/etroynov/zig-school/assets/4591518/f7c59ed9-deb6-462d-9d1f-0bb1da2c90ff">

**Comment by Panth1823** [comment]
Hey @etroynov i would like to work on this but can u please give more details?

**Comment by etroynov** [comment]
@Panth1823 Welcome :)

The task is really simple, you should just add the new section in the sidebar, also you have to create a new page with the title "Why Zig?" and copy info from the official site:
https://ziglang.org/

This block:
![Uploading Screenshot 2023-10-08 at 18.37.47.png…]()

**Comment by rLukoyanov** [comment]
Hey @etroynov i would like to work on this but can u please give more details?

**Comment by etroynov** [comment]
released
